### ISSUE TITLE
General Question: Can the generated MAZE images be solved if printed out?

### ISSUE THREAD

**Issue by inglesuniversal** [vikvikvr/maze-generator#1]
That would be double the FUN

Thanks for such a cool project!

**Comment by vikvikvr** [comment]
As it stands, the maze doesn't have any entry/exit (all borders have walls).

Are you suggesting to break 2 outer cells and then let the user save a picture with a stroke that shows an optimal solution?

I'm on mobile at the moment, will post a picture shortly to see if I understand correctly

**Comment by inglesuniversal** [comment]
What you are saying would be extremely awesome... but hidden until certain period of customizable time to complete.

Right there you would have a GREAT GAME.... The current version is already amazing for an IMAGE GALLERY just as it is.

Thanks for taking your valuable time to read my suggestion / feature request.

Best regards

**Comment by vikvikvr** [comment]
@inglesuniversal you can now download the image once the maze has been generated

#3 

have a play with it here https://master--maze-generator-cw.netlify.app/
